version: '3.7'
services:
  db:
    image: postgres:16
    container_name: notes_db
    volumes:
      - ./config.yaml:/src/app/config/config.yaml
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 3
  notes:
    image: notes_image
    build:
      context: .
    container_name: notes_app
    volumes:
      - ./config.yaml:/src/app/config/config.yaml
    command: /bin/bash -c "alembic upgrade head && gunicorn src.app.asgi:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"
    depends_on:
      - db
